create table public.events (
  id bigint generated by default as identity not null,
  visitor_id text null,
  event_type text null,
  timestamp timestamp with time zone not null default now(),
  score_impact smallint null default '0'::smallint,
  listing_id text null,
  client_id text not null default 'client-abc'::text,
  constraint events_pkey primary key (id),
  constraint events_listing_id_fkey foreign KEY (listing_id) references listings (id) ON DELETE CASCADE,
  constraint events_visitor_id_fkey foreign KEY (visitor_id) references visitors (visitor_id) ON DELETE CASCADE
) TABLESPACE pg_default;