create table public.events (
  id bigint generated by default as identity not null,
  visitor_id text null,
  event_type text null,
  timestamp timestamp with time zone not null default now(),
  score_impact smallint null default '0'::smallint,
  listing_id text null,
  client_id uuid not null,
  listing_uuid uuid null,
  constraint events_pkey primary key (id),
  constraint events_listing_uuid_fkey foreign KEY (listing_uuid) references listings (listing_uuid),
  constraint events_visitor_id_fkey foreign KEY (visitor_id) references visitors (visitor_id) on delete CASCADE
) TABLESPACE pg_default;